webtalk_init -webtalk_dir U:\\ETG\\master_ee_224\\src\\firmware\\zybo_z7_firmware\\full_firmware_build\\full_firmware_build.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-02-10 12:58:44" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174156856_174156857_210694690_929" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "isj2m34pf617ar7erh3pscoc9t" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) E-2124G CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.147 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1581358042508" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1581358042508"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1581361124866"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1581361124866"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1581361124866"
webtalk_add_data -client sdk -key DebugCount -value "10" -context "sdk\\\\bsp/1581361124866"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1581361124866"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1581361124866"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1581361124866"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1581361124866"
webtalk_transmit -clientid 3611813733 -regid "174156856_174156857_210694690_929" -xml U:\\ETG\\master_ee_224\\src\\firmware\\zybo_z7_firmware\\full_firmware_build\\full_firmware_build.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html U:\\ETG\\master_ee_224\\src\\firmware\\zybo_z7_firmware\\full_firmware_build\\full_firmware_build.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm U:\\ETG\\master_ee_224\\src\\firmware\\zybo_z7_firmware\\full_firmware_build\\full_firmware_build.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
