webtalk_init -webtalk_dir U:\\master_ee_224\\src\\firmware\\zybo_z7_firmware\\full_firmware_build\\full_firmware_build.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-12-05 16:55:58" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174156856_174156857_210694690_929" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "t63bjl9mmmslgg1hoson09657r" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3504 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.102 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1575586422681" -context "sdk\\\\bsp/1575586422681"
webtalk_add_data -client sdk -key hwid -value "1573523990952" -context "sdk\\\\bsp/1575586422681"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1575586422681"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1575586422681"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1575586422681"
webtalk_add_data -client sdk -key uid -value "1575586451825" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key hwid -value "1573523990952" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key bspid -value "1575586422681" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key projSize -value "713.8671875" -context "sdk\\\\application/1575586451825"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1575586558048"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1575586558048"
webtalk_add_data -client sdk -key BootgenCount -value "2" -context "sdk\\\\bsp/1575586558048"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1575586558048"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1575586558048"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1575586558048"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1575586558048"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1575586558048"
webtalk_transmit -clientid 1383533529 -regid "174156856_174156857_210694690_929" -xml U:\\master_ee_224\\src\\firmware\\zybo_z7_firmware\\full_firmware_build\\full_firmware_build.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html U:\\master_ee_224\\src\\firmware\\zybo_z7_firmware\\full_firmware_build\\full_firmware_build.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm U:\\master_ee_224\\src\\firmware\\zybo_z7_firmware\\full_firmware_build\\full_firmware_build.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
